"""
PDF generator utility for reorder list exports.
Uses ReportLab to create formatted PDF documents.
"""

import io
from typing import List, Dict, Any
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT


def generate_reorder_pdf(
    reorder_list: List[Dict[str, Any]],
    summary: Dict[str, Any],
    shop_name: str = "StockSense Store",
) -> bytes:
    """
    Generate a PDF reorder report.

    Args:
        reorder_list: List of reorder item dicts with keys:
            product_name, current_stock, forecast_demand, reorder_qty,
            urgency, supplier_name, estimated_cost
        summary: Summary dict with keys:
            total_items, estimated_total_cost, most_urgent_product
        shop_name: Name of the shop for the header.

    Returns:
        PDF file as bytes.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    elements = []

    # Title
    title_style = ParagraphStyle(
        "Title",
        parent=styles["Heading1"],
        fontSize=18,
        alignment=TA_CENTER,
        spaceAfter=12,
    )
    elements.append(Paragraph("📦 StockSense Reorder Report", title_style))

    # Subtitle — shop name and date
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=11,
        alignment=TA_CENTER,
        spaceAfter=20,
        textColor=colors.grey,
    )
    elements.append(
        Paragraph(
            f"{shop_name} — Generated {datetime.now().strftime('%d %b %Y, %I:%M %p')}",
            subtitle_style,
        )
    )

    # Summary section
    summary_style = ParagraphStyle(
        "Summary",
        parent=styles["Normal"],
        fontSize=10,
        spaceAfter=6,
    )
    elements.append(Paragraph(f"<b>Total Items to Reorder:</b> {summary.get('total_items', 0)}", summary_style))
    elements.append(
        Paragraph(
            f"<b>Estimated Total Cost:</b> ₹{summary.get('estimated_total_cost', 0):,.2f}",
            summary_style,
        )
    )
    elements.append(
        Paragraph(
            f"<b>Most Urgent:</b> {summary.get('most_urgent_product', 'N/A')}",
            summary_style,
        )
    )
    elements.append(Spacer(1, 20))

    # Table header
    table_data = [
        ["#", "Product", "Current\nStock", "Forecast\nDemand", "Reorder\nQty", "Urgency", "Supplier", "Est. Cost (₹)"]
    ]

    for idx, item in enumerate(reorder_list, 1):
        table_data.append([
            str(idx),
            item.get("product_name", ""),
            str(int(item.get("current_stock", 0))),
            str(int(item.get("forecast_demand", 0))),
            str(int(item.get("reorder_qty", 0))),
            item.get("urgency", "low").upper(),
            item.get("supplier_name", "N/A"),
            f"₹{item.get('estimated_cost', 0):,.0f}",
        ])

    # Style the table
    table = Table(table_data, repeatRows=1)
    table.setStyle(TableStyle([
        # Header
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("ALIGN", (0, 0), (-1, 0), "CENTER"),
        ("VALIGN", (0, 0), (-1, 0), "MIDDLE"),
        # Body
        ("FONTSIZE", (0, 1), (-1, -1), 8),
        ("ALIGN", (0, 1), (0, -1), "CENTER"),
        ("ALIGN", (2, 1), (4, -1), "CENTER"),
        ("ALIGN", (5, 1), (5, -1), "CENTER"),
        ("ALIGN", (7, 1), (7, -1), "RIGHT"),
        # Grid
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
        # Padding
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
    ]))

    elements.append(table)

    # Footer
    elements.append(Spacer(1, 30))
    footer_style = ParagraphStyle(
        "Footer",
        parent=styles["Normal"],
        fontSize=8,
        alignment=TA_CENTER,
        textColor=colors.grey,
    )
    elements.append(
        Paragraph(
            "Generated by StockSense — AI-Powered Inventory Management",
            footer_style,
        )
    )

    doc.build(elements)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
